image: node:8.12.0-jessie

before_script:
  - node -v
  - npm -v

stages:
  - prep
  - build 
  - deploy

prep:
  stage: prep
  script: 
    - npm install 
  artifacts:
    paths:
      - node_modules
  cache:
    paths:
      - node_modules

build:
  stage: build
  script:
    - npm run deploy
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - master
  script: echo ""

